### ISSUE TITLE
NameError: global name 'is_executable' is not defined

### ISSUE THREAD

**Issue by noinkling** [danpe/QuickRails#2]
Whenever I use the bundle install shortcut or attempt to update the generator/rake/capistrano commands, I get this error:

    File "./QuickRails.py", line 52, in command_with_ruby_env
    NameError: global name 'is_executable' is not defined

Running Ubuntu 12.04.2, Sublime Text 2.0.2 (released recently). Using RVM, Ruby 2.0.0 and Rails 4. QuickRails was installed via the Sublime Text package manager.

Removing the `and is_executable(rvm_cmd)` part of the condition on that line seems to make things work.

**Comment by danpe** [comment]
Hey, Sorry guys !
It's all been fixed now ! ;)
